import Foundation
import os

/// Public inventory returned by the authenticated pre-key service.
public struct IOSPreKeyInventory: Equatable, Sendable {
    public let deviceID: String
    public let profileRevision: UInt64
    public let oneTimeCurvePreKeys: UInt32
    public let oneTimeKEMPreKeys: UInt32

    public init(deviceID: String, profileRevision: UInt64,
                oneTimeCurvePreKeys: UInt32, oneTimeKEMPreKeys: UInt32) throws {
        guard IOSClient.isCanonicalUUID(deviceID),
              profileRevision <= UInt64(Int64.max),
              oneTimeCurvePreKeys <= 100,
              oneTimeKEMPreKeys <= 100,
              profileRevision != 0 || (oneTimeCurvePreKeys == 0 && oneTimeKEMPreKeys == 0) else {
            throw IOSPreKeyError.invalidResponse
        }
        self.deviceID = deviceID
        self.profileRevision = profileRevision
        self.oneTimeCurvePreKeys = oneTimeCurvePreKeys
        self.oneTimeKEMPreKeys = oneTimeKEMPreKeys
    }
}

/// Exact public protobuf bytes generated by the shared Rust core. The host
/// keeps this value opaque and the core keeps it in its durable retry slot.
public struct IOSPreKeyUpload: Sendable {
    public let deviceID: String
    public let profileRevision: UInt64
    public let uploadID: String
    public let protobuf: Data

    public init(deviceID: String, profileRevision: UInt64, uploadID: String,
                protobuf: Data) throws {
        guard IOSClient.isCanonicalUUID(deviceID),
              IOSClient.isCanonicalUUID(uploadID),
              profileRevision > 0,
              profileRevision <= UInt64(Int64.max),
              !protobuf.isEmpty,
              protobuf.count <= 256 * 1024 else {
            throw IOSPreKeyError.invalidUpload
        }
        self.deviceID = deviceID
        self.profileRevision = profileRevision
        self.uploadID = uploadID
        self.protobuf = protobuf
    }

    public init(protobuf: Data) throws {
        var reader = IOSProtobufReader(protobuf)
        var version: UInt32?
        var deviceID: String?
        var revision: UInt64?
        var uploadID: String?
        while !reader.isAtEnd {
            let field = try reader.readField()
            switch field.number {
            case 1 where field.wireType == 0:
                version = try reader.readUInt32()
            case 2 where field.wireType == 2:
                deviceID = try reader.readString(maximum: 64)
            case 3 where field.wireType == 0:
                revision = try reader.readUInt64()
            case 7 where field.wireType == 2:
                uploadID = try reader.readString(maximum: 64)
            default:
                try reader.skip(wireType: field.wireType)
            }
        }
        guard version == 1, let deviceID, let revision, let uploadID else {
            throw IOSPreKeyError.invalidUpload
        }
        try self.init(
            deviceID: deviceID, profileRevision: revision,
            uploadID: uploadID, protobuf: protobuf)
    }
}

/// Claimed protobuf bytes are verified by the shared Rust core. Swift never
/// interprets or trusts public key fields from an unverified response.
public struct IOSClaimedPreKeyBundle: Sendable {
    public let deviceID: String
    public let protobuf: Data

    public init(deviceID: String, protobuf: Data) throws {
        guard IOSClient.isCanonicalUUID(deviceID),
              !protobuf.isEmpty,
              protobuf.count <= 256 * 1024 else {
            throw IOSPreKeyError.invalidResponse
        }
        self.deviceID = deviceID
        self.protobuf = protobuf
    }
}

/// Public directory data plus the authenticated MLS KeyPackage selected by a
/// host directory adapter. Pre-key bundles are added only after claiming.
public struct IOSRecipientDeviceDescriptor: Sendable {
    public let userID: String
    public let deviceID: String
    public let identityPublicKey: Data
    public let mlsCredential: Data
    public let mlsKeyPackage: Data

    public init(userID: String, deviceID: String, identityPublicKey: Data,
                mlsCredential: Data, mlsKeyPackage: Data) throws {
        guard IOSClient.isCanonicalUUID(userID),
              IOSClient.isCanonicalUUID(deviceID),
              identityPublicKey.count == 32,
              !mlsCredential.isEmpty,
              mlsCredential.count <= 1024,
              !mlsKeyPackage.isEmpty,
              mlsKeyPackage.count <= IOSConnectionManager.maximumFrameBytes else {
            throw IOSPreKeyError.invalidRecipient
        }
        self.userID = userID
        self.deviceID = deviceID
        self.identityPublicKey = identityPublicKey
        self.mlsCredential = mlsCredential
        self.mlsKeyPackage = mlsKeyPackage
    }
}

/// A directory adapter must authenticate the public device snapshot and return
/// one current MLS KeyPackage for each recipient device that has published one.
/// Devices that registered but never opened a client are omitted.
public protocol IOSDirectChatDirectory: AnyObject {
    func queryRecipientDevices(accessToken: String, recipientUserID: String)
        async throws -> [IOSRecipientDeviceDescriptor]
}

/// Supplies the current MLS KeyPackage for one directory device. KeyPackages
/// are public bootstrap material, but must still be bound to the exact device
/// and credential returned by the directory. The provider must not retain the
/// access token after this call.
public protocol IOSMLSKeyPackageProvider: AnyObject {
    func keyPackage(accessToken: String, userID: String, deviceID: String,
                    mlsNodeID: String, mlsCredential: Data) async throws -> Data
}

/// Concrete HTTPS directory adapter used by macOS and iOS hosts. Recipients
/// resolve by stable user ID; pre-key claims remain in `IOSDirectMessaging`.
public final class IOSUsernameDirectoryChatAdapter: IOSDirectChatDirectory {
    private let directoryClient: IOSUsernameAuthClient
    private let keyPackageProvider: any IOSMLSKeyPackageProvider

    public init(directoryClient: IOSUsernameAuthClient,
                handlesByUserID: [String: String],
                keyPackageProvider: any IOSMLSKeyPackageProvider) {
        self.directoryClient = directoryClient
        // Retain the argument for source compatibility. Routing uses stable IDs.
        _ = handlesByUserID
        self.keyPackageProvider = keyPackageProvider
    }

    public func queryRecipientDevices(accessToken: String, recipientUserID: String)
        async throws -> [IOSRecipientDeviceDescriptor] {
        guard !accessToken.isEmpty, accessToken.utf8.count <= 4096,
              IOSClient.isCanonicalUUID(recipientUserID) else {
            throw IOSPreKeyError.invalidRecipient
        }
        let directory = try await directoryClient.lookup(
            userID: recipientUserID, accessToken: accessToken)
        guard directory.userID == recipientUserID,
              !directory.devices.isEmpty,
              directory.devices.count <= 100 else {
            throw IOSPreKeyError.invalidRecipient
        }
        return try await IOSRecipientDeviceLookup.descriptors(
            for: directory.devices,
            userID: directory.userID,
            accessToken: accessToken,
            keyPackageProvider: keyPackageProvider)
    }
}

/// Keeps devices that have published an MLS KeyPackage and skips the rest.
public enum IOSRecipientDeviceLookup {
    public static func descriptors(
        for devices: [IOSDirectoryDevice],
        userID: String,
        accessToken: String,
        keyPackageProvider: any IOSMLSKeyPackageProvider
    ) async throws -> [IOSRecipientDeviceDescriptor] {
        guard !devices.isEmpty, devices.count <= 100 else {
            throw IOSPreKeyError.invalidRecipient
        }
        var seen = Set<String>()
        var descriptors = [IOSRecipientDeviceDescriptor]()
        descriptors.reserveCapacity(devices.count)
        var missingPackages = 0
        var tokenFailures = 0
        for device in devices {
            guard seen.insert(device.deviceID).inserted else {
                throw IOSPreKeyError.invalidRecipient
            }
            let keyPackage: Data
            do {
                keyPackage = try await keyPackageProvider.keyPackage(
                    accessToken: accessToken,
                    userID: userID,
                    deviceID: device.deviceID,
                    mlsNodeID: device.mlsNodeID,
                    mlsCredential: device.mlsCredential)
            } catch IOSPreKeyError.notFound {
                missingPackages += 1
                continue
            } catch IOSPreKeyError.invalidToken {
                // Older account servers answer 401 when a device has no
                // KeyPackage. A rejected token fails every device the same way.
                tokenFailures += 1
                continue
            }
            descriptors.append(try IOSRecipientDeviceDescriptor(
                userID: userID,
                deviceID: device.deviceID,
                identityPublicKey: device.identityPublicKey,
                mlsCredential: device.mlsCredential,
                mlsKeyPackage: keyPackage))
        }
        if !descriptors.isEmpty { return descriptors }
        if tokenFailures == devices.count && missingPackages == 0 {
            throw IOSPreKeyError.invalidToken
        }
        throw IOSPreKeyError.invalidRecipient
    }
}

/// Authenticated protobuf boundary for account-auth pre-key operations.
/// Access tokens are supplied by the caller and are never retained here.
public protocol IOSPreKeyAPI: AnyObject {
    func inventory(accessToken: String) async throws -> IOSPreKeyInventory
    func upload(accessToken: String, upload: IOSPreKeyUpload)
        async throws -> IOSPreKeyInventory
    func claim(accessToken: String, deviceID: String)
        async throws -> IOSClaimedPreKeyBundle
}

public enum IOSPreKeyError: Error, Equatable {
    case invalidEndpoint
    case invalidToken
    case invalidUpload
    case invalidRecipient
    case invalidResponse
    case serviceRejected
    /// This device has not published the requested pre-key or KeyPackage.
    case notFound
    /// The account service already has this device's pre-key profile.
    case conflict
}

/// URLSession adapter for the account-auth protobuf pre-key routes.
public final class IOSPreKeyHTTPClient: IOSPreKeyAPI, Sendable {
    fileprivate static let maximumResponseBytes = 256 * 1024
    private let baseURL: URL
    private let urlSession: URLSession

    public init(baseURL: URL, urlSession: URLSession = .shared) throws {
        guard baseURL.user == nil,
              baseURL.query == nil,
              baseURL.fragment == nil,
              baseURL.path.isEmpty || baseURL.path == "/",
              let scheme = baseURL.scheme?.lowercased(),
              let host = baseURL.host?.lowercased(),
              scheme == "https" || (scheme == "http" && Self.isLoopback(host)) else {
            throw IOSPreKeyError.invalidEndpoint
        }
        self.baseURL = baseURL
        self.urlSession = urlSession
    }

    public func inventory(accessToken: String) async throws -> IOSPreKeyInventory {
        let request = try makeRequest(path: "v1/prekeys/status", method: "GET",
                                      accessToken: accessToken)
        let response = try await requestData(request)
        return try Self.decodeInventory(response)
    }

    public func upload(accessToken: String, upload: IOSPreKeyUpload)
        async throws -> IOSPreKeyInventory {
        let request = try makeRequest(path: "v1/prekeys", method: "PUT",
                                      accessToken: accessToken, body: upload.protobuf)
        let response = try await requestData(request)
        let inventory = try Self.decodeInventory(response)
        guard inventory.deviceID == upload.deviceID,
              inventory.profileRevision >= upload.profileRevision else {
            throw IOSPreKeyError.invalidResponse
        }
        return inventory
    }

    public func claim(accessToken: String, deviceID: String)
        async throws -> IOSClaimedPreKeyBundle {
        guard IOSClient.isCanonicalUUID(deviceID) else {
            throw IOSPreKeyError.invalidRecipient
        }
        let request = try makeRequest(
            path: "v1/prekeys/\(deviceID)/claim", method: "POST",
            accessToken: accessToken)
        let response = try await requestData(request)
        return try IOSClaimedPreKeyBundle(deviceID: deviceID, protobuf: response)
    }

    /// MLS KeyPackages are public bootstrap material, bound to the device by
    /// the signed MLS credential. The package itself remains opaque to Swift.
    public func uploadMLSKeyPackage(accessToken: String, keyPackage: Data) async throws {
        guard !keyPackage.isEmpty, keyPackage.count <= Self.maximumResponseBytes else {
            throw IOSPreKeyError.invalidUpload
        }
        let request = try makeRequest(
            path: "v1/mls/key-package", method: "PUT",
            accessToken: accessToken, body: keyPackage)
        do {
            let (body, response) = try await urlSession.data(for: request)
            guard let http = response as? HTTPURLResponse else {
                Self.recordFailure(request, status: -1, body: Data())
                throw IOSPreKeyError.serviceRejected
            }
            if http.statusCode == 409 { throw IOSPreKeyError.conflict }
            guard http.statusCode == 204 else {
                Self.recordFailure(request, status: http.statusCode, body: body)
                throw IOSPreKeyError.serviceRejected
            }
        } catch let error as IOSPreKeyError {
            throw error
        } catch {
            Self.recordFailure(request, status: -1, body: Data(String(describing: error).utf8))
            throw IOSPreKeyError.serviceRejected
        }
    }

    public func downloadMLSKeyPackage(accessToken: String, deviceID: String) async throws -> Data {
        guard IOSClient.isCanonicalUUID(deviceID) else {
            throw IOSPreKeyError.invalidRecipient
        }
        let request = try makeRequest(
            path: "v1/mls/key-package/\(deviceID)", method: "GET",
            accessToken: accessToken)
        return try await requestData(request)
    }

    private func makeRequest(path: String, method: String, accessToken: String,
                             body: Data? = nil) throws -> URLRequest {
        guard !accessToken.isEmpty, accessToken.utf8.count <= 4096 else {
            throw IOSPreKeyError.invalidToken
        }
        var request = URLRequest(url: baseURL.appendingPathComponent(path))
        request.httpMethod = method
        request.httpShouldHandleCookies = false
        request.setValue("application/x-protobuf", forHTTPHeaderField: "Accept")
        request.setValue("no-store", forHTTPHeaderField: "Cache-Control")
        request.setValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
        if let body {
            guard body.count <= Self.maximumResponseBytes else {
                throw IOSPreKeyError.invalidUpload
            }
            request.setValue("application/x-protobuf", forHTTPHeaderField: "Content-Type")
            request.httpBody = body
        }
        return request
    }

    private func requestData(_ request: URLRequest) async throws -> Data {
        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await urlSession.data(for: request)
        } catch {
            throw IOSPreKeyError.serviceRejected
        }
        guard let http = response as? HTTPURLResponse else {
            Self.recordFailure(request, status: -1, body: data)
            throw IOSPreKeyError.serviceRejected
        }
        if http.statusCode == 409 { throw IOSPreKeyError.conflict }
        if http.statusCode == 401 { throw IOSPreKeyError.invalidToken }
        if http.statusCode == 404 { throw IOSPreKeyError.notFound }
        guard (200..<300).contains(http.statusCode),
              data.count <= Self.maximumResponseBytes,
              Self.isProtobuf(http.value(forHTTPHeaderField: "Content-Type")) else {
            Self.recordFailure(request, status: http.statusCode, body: data)
            throw IOSPreKeyError.serviceRejected
        }
        return data
    }

    private static func decodeInventory(_ data: Data) throws -> IOSPreKeyInventory {
        var reader = IOSProtobufReader(data)
        var version: UInt32?
        var deviceID: String?
        // Protobuf omits scalar fields whose value is zero. An account with
        // no pre-key profile therefore returns only the version and device
        // fields; the omitted inventory counters are valid zeroes.
        var revision: UInt64 = 0
        var curveCount: UInt32 = 0
        var kemCount: UInt32 = 0
        while !reader.isAtEnd {
            let field = try reader.readField()
            switch field.number {
            case 1 where field.wireType == 0:
                version = try reader.readUInt32()
            case 2 where field.wireType == 2:
                deviceID = try reader.readString(maximum: 64)
            case 3 where field.wireType == 0:
                revision = try reader.readUInt64()
            case 4 where field.wireType == 0:
                curveCount = try reader.readUInt32()
            case 5 where field.wireType == 0:
                kemCount = try reader.readUInt32()
            default:
                try reader.skip(wireType: field.wireType)
            }
        }
        guard version == 1,
              let deviceID else {
            throw IOSPreKeyError.invalidResponse
        }
        return try IOSPreKeyInventory(
            deviceID: deviceID,
            profileRevision: revision,
            oneTimeCurvePreKeys: curveCount,
            oneTimeKEMPreKeys: kemCount)
    }

    private static func recordFailure(_ request: URLRequest, status: Int, body: Data) {
        let path = request.url?.path ?? "?"
        let text = String(data: body.prefix(400), encoding: .utf8) ?? "<binary>"
        Logger(subsystem: "ai.links.Links", category: "prekeys")
            .error("prekey failure \(request.httpMethod ?? "?", privacy: .public) \(path, privacy: .public) status=\(status) body=\(text, privacy: .public)")
    }

    private static func isProtobuf(_ value: String?) -> Bool {
        guard let value else { return false }
        return value.split(separator: ";", maxSplits: 1, omittingEmptySubsequences: true)
            .first.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            == "application/x-protobuf"
    }

    private static func isLoopback(_ host: String) -> Bool {
        host == "localhost" || host == "127.0.0.1" || host == "::1"
    }
}

/// Authenticated recipient KeyPackage fetcher used by directory adapters.
public final class IOSHTTPMLSKeyPackageProvider: IOSMLSKeyPackageProvider, Sendable {
    private let api: IOSPreKeyHTTPClient

    public init(api: IOSPreKeyHTTPClient) {
        self.api = api
    }

    public func keyPackage(accessToken: String, userID: String, deviceID: String,
                           mlsNodeID: String, mlsCredential: Data) async throws -> Data {
        guard IOSClient.isCanonicalUUID(userID), IOSClient.isCanonicalUUID(deviceID),
              IOSClient.isCanonicalUUID(mlsNodeID), !mlsCredential.isEmpty else {
            throw IOSPreKeyError.invalidRecipient
        }
        return try await api.downloadMLSKeyPackage(accessToken: accessToken, deviceID: deviceID)
    }
}

private struct IOSProtobufField {
    let number: Int
    let wireType: Int
}

private struct IOSProtobufReader {
    private let bytes: [UInt8]
    private var offset = 0

    init(_ data: Data) {
        bytes = Array(data)
    }

    var isAtEnd: Bool { offset == bytes.count }

    mutating func readField() throws -> IOSProtobufField {
        let tag = try readVarint()
        let number = tag >> 3
        let wireType = tag & 7
        guard number > 0, number <= UInt64(Int.max), wireType <= 5,
              wireType != 4 else { throw IOSPreKeyError.invalidResponse }
        return IOSProtobufField(number: Int(number), wireType: Int(wireType))
    }

    mutating func readUInt32() throws -> UInt32 {
        let value = try readVarint()
        guard value <= UInt64(UInt32.max) else { throw IOSPreKeyError.invalidResponse }
        return UInt32(value)
    }

    mutating func readUInt64() throws -> UInt64 {
        try readVarint()
    }

    mutating func readString(maximum: Int) throws -> String {
        let data = try readLengthDelimited(maximum: maximum)
        guard let string = String(data: data, encoding: .utf8), !string.isEmpty else {
            throw IOSPreKeyError.invalidResponse
        }
        return string
    }

    mutating func skip(wireType: Int) throws {
        switch wireType {
        case 0:
            _ = try readVarint()
        case 1:
            try advance(by: 8)
        case 2:
            _ = try readLengthDelimited(maximum: IOSPreKeyHTTPClient.maximumResponseBytes)
        case 5:
            try advance(by: 4)
        default:
            throw IOSPreKeyError.invalidResponse
        }
    }

    private mutating func readVarint() throws -> UInt64 {
        var value: UInt64 = 0
        for index in 0..<10 {
            guard offset < bytes.count else { throw IOSPreKeyError.invalidResponse }
            let byte = bytes[offset]
            offset += 1
            if index == 9 && byte > 1 { throw IOSPreKeyError.invalidResponse }
            value |= UInt64(byte & 0x7f) << UInt64(index * 7)
            if byte & 0x80 == 0 { return value }
        }
        throw IOSPreKeyError.invalidResponse
    }

    private mutating func readLengthDelimited(maximum: Int) throws -> Data {
        let length = try readVarint()
        guard length <= UInt64(maximum),
              length <= UInt64(bytes.count - offset) else {
            throw IOSPreKeyError.invalidResponse
        }
        let end = offset + Int(length)
        defer { offset = end }
        return Data(bytes[offset..<end])
    }

    private mutating func advance(by count: Int) throws {
        guard count <= bytes.count - offset else { throw IOSPreKeyError.invalidResponse }
        offset += count
    }
}

public extension SharedClientCore {
    /// The concrete Rust binding calls `prekeys::maintain_inventory`. It
    /// persists the exact generated protobuf before upload and retries it
    /// before creating another key batch.
    func maintainPreKeyInventory(accessToken: String, api: any IOSPreKeyAPI)
        async throws -> IOSPreKeyInventory {
        throw IOSMessagingError.preKeyBootstrapUnavailable
    }

    /// The concrete Rust binding claims each recipient bundle, verifies it
    /// against the directory key, and calls the shared direct-MLS coordinator.
    func initializeDirectConversation(
        conversationID: String,
        recipientUserID: String,
        recipientDevices: [IOSClaimedRecipientDevice],
        transport: any IOSCoreTransport) throws {
        throw IOSMessagingError.preKeyBootstrapUnavailable
    }
}

/// Claimed material handed to the Rust binding. The Swift host cannot mark a
/// bundle verified; only the shared core can do that from these inputs.
public struct IOSClaimedRecipientDevice: Sendable {
    public let userID: String
    public let deviceID: String
    public let identityPublicKey: Data
    public let preKeyBundle: Data
    public let mlsCredential: Data
    public let mlsKeyPackage: Data

    public init(descriptor: IOSRecipientDeviceDescriptor,
                bundle: IOSClaimedPreKeyBundle) throws {
        guard descriptor.deviceID == bundle.deviceID else {
            throw IOSPreKeyError.invalidRecipient
        }
        self.userID = descriptor.userID
        self.deviceID = descriptor.deviceID
        self.identityPublicKey = descriptor.identityPublicKey
        self.preKeyBundle = bundle.protobuf
        self.mlsCredential = descriptor.mlsCredential
        self.mlsKeyPackage = descriptor.mlsKeyPackage
    }
}
