[package]
name = "links-identity"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bip39.workspace = true
hkdf.workspace = true
links-protocol.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize.workspace = true
uuid.workspace = true
ed25519-dalek = { version = "2", features = ["zeroize"] }
getrandom.workspace = true
tls_codec = { version = "0.4", features = ["derive"] }
